tags:
    - docker
before_script:
    - source /usr/local/nvm/nvm.sh
    - nvm install v6.12.0
    - nvm use v6.12.0
    - npm i
cache:
    untracked: true
unit-test:
    stage: test
    script:
        - npm test
